{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metabase-k8s.name" . }}-config
  labels:
    {{- include "metabase-k8s.labels" . | nindent 4 }}
data:
  # Metabase listens on 0.0.0.0 by default
  MB_JETTY_HOST: "0.0.0.0"
  # Add additional Metabase configuration options here as needed.
{{- end }}
