{{- if and .Values.rbac.create .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metabase-k8s.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
