{{- if and .Values.rbac.create .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8-metabase.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8-metabase.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "k8-metabase.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
