{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8-metabase.name" . }}-secret
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  # You can set secret values such as the Metabase admin password here.
  # Example: METABASE_PASSWORD: "your-secret-password"
{{- end }}
