{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8-metabase.name" . }}-headless
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ include "k8-metabase.name" . }}
{{- end }}
