{{- if and .Values.rbac.create .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metabase-k8s.name" . }}
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
{{- end }}
