{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase-k8s.name" . }}
  labels:
    {{- include "k8-metabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "metabase-k8s.name" . }}
{{- end }}
