helmCommands:
  # 💡 Template Command: Render templates without installing
  template: |
    helm template metabase-k8s . --values values.yaml

  # 💡 Lint Command: Validate chart syntax
  lint: |
    helm lint .

  # 💡 Dry-run Command: Simulate installation without deploying
  dryRun: |
    helm install metabase-k8s . --values values.yaml --namespace metabase-k8s-ns --dry-run --debug

  # 💡 Install Command: Install the chart into Kubernetes
  install: |
    helm install metabase-k8s . --values values.yaml --namespace metabase-k8s-ns  --debug

  # 💡 Upgrade Command: Upgrade an existing release with updated chart values
  upgrade: |
    helm upgrade metabase-k8s . --values values.yaml --namespace metabase-k8s-ns

  # 💡 Uninstall Command: Remove the release from Kubernetes
  uninstall: |
    helm uninstall metabase-k8s --namespace metabase-k8s-ns

  # 💡 Status Command: Check the release status
  status: |
    helm status metabase-k8s --namespace metabase-k8s-ns

  # 💡 List Command: List all installed Helm releases
  list: |
    helm list --namespace metabase-k8s-ns

  # 💡 History Command: View the revision history of a release
  history: |
    helm history metabase-k8s --namespace metabase-k8s-ns

  # 💡 Rollback Command: Roll back to a previous release
  rollback: |
    helm rollback metabase-k8s <REVISION> --namespace metabase-k8s-ns
