name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Build with Helm
        run: |
          mkdir -p .public
          cp -r charts .public/
          cp README.md .public/
          cp LICENSE .public/
          
          # Generate index.html
          cat > .public/index.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>ArconixForge Helm Repository</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; max-width: 800px; margin: 0 auto; }
              h1 { color: #333; }
              code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }
              pre { background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }
            </style>
          </head>
          <body>
            <h1>ArconixForge Helm Repository</h1>
            <p>Welcome to the ArconixForge Helm Repository. You can use this repository by adding it to your Helm:</p>
            <pre><code>helm repo add arconixforge https://arconixforge.github.io/helm-charts
                helm repo update</code></pre>
            <h2>Available Charts</h2>
            <ul>
              <li><a href="https://github.com/ArconixForge/helm-charts/tree/main/charts/metabase-k8s">metabase-k8s</a> - A production-ready Helm chart for deploying Metabase on Kubernetes</li>
            </ul>
          </body>
          </html>
          EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2