name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/metabase-k8s/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Package Helm Chart
        run: |
          # Create packaged directory if it doesn't exist
          mkdir -p packaged
          
          # Package the chart
          helm package charts/metabase-k8s -d packaged/
          
          # Update the Helm repository index
          helm repo index packaged/ --url https://arconixforge.github.io/metabase-k8s/packaged

      - name: Commit and Push Changes
        run: |
          git add packaged/
          git commit -m "Update packaged charts" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "metabase-k8s-$(grep 'version:' charts/metabase-k8s/Chart.yaml | awk '{print $2}')"
          files: packaged/metabase-k8s-*.tgz
          generate_release_notes: true